

TEST - använd ej

<p/>
Här kan du göra en intresseanmälan. När du fyllt i samtliga fält tryck på knappen Skicka in. Om du ångrar dig och inte vill ha kontakt, tryck istället på knappen rensa. Om du ångrar dig efter att du skickat iväg dina svar, vänligen ring 018-471 7128.

<p/>
<form method="POST" action="%CURRENTURL%">

Kontaktorsak:
<div style="clear: both;" />
<textarea name="reason" cols="40" rows="4" >
Beskriv mycket kort skälet till varför du vill ha kontakt.
</textarea>

<div style="clear: both;" />
Namn: <div style="clear: both;" />
<input type="text" name="name" />
<div style="clear: both;" />

Adress:

<div style="clear: both;" />
<input type="text" name="address" />
<div style="clear: both;" />
<br />
Postnummer:
<div style="clear: both;" />
<input type="text" name="zip" />

<div style="clear: both;" />
Ort:
<div style="clear: both;" />
<input type="text" name="location" />
<div style="clear: both;" />

Mobilnummer:
<div style="clear: both;" />
<input type="text" name="cellphone" />

<div style="clear: both;" />

E-post:
<div style="clear: both;" />
<input type="text" name="mail" />

<div style="clear: both;" />

Dagens datum, ÅÅMMDD (t ex 110115):
<div style="clear: both;" />
<input type="text" name="date" />
  (Pontus not; Varför?)

<div style="clear: both; margin-top: 2em;" />
  <input type="submit" name="skickat" value=" Skicka in " />


</form>

Dina personuppgifter omfattas av sjukvårdslagen (SVL).
