<div>


Här kan du göra en intresseanmälan. När du fyllt i samtliga fält tryck på knappen Skicka in. Om du ångrar dig efter att du skickat iväg dina svar, vänligen ring 018-471 2344.

<p/>
<form method="post" action="https://www-hotel.uu.se/psykmott/mott.php">

Kontaktorsak:
<div style="clear: both;" ></div>
<textarea name="reason" cols="40" rows="4" >
Beskriv mycket kort skälet till varför du vill ha kontakt.
</textarea>

<div style="clear: both;" ></div>
Namn: <div style="clear: both;" ></div>
<input type="text" name="name" />
<div style="clear: both;" ></div>

Adress:

<div style="clear: both;" ></div>
<input type="text" name="address" />
<div style="clear: both;" ></div>

Postnummer:
<div style="clear: both;" ></div>
<input type="text" name="zip" />

<div style="clear: both;" ></div>
Ort:
<div style="clear: both;" ></div>
<input type="text" name="location" />
<div style="clear: both;" ></div>

Mobilnummer:
<div style="clear: both;" ></div>
<input type="text" name="cellphone" />

<div style="clear: both;" ></div>

E-post:
<div style="clear: both;" ></div>
<input type="text" name="mail" />

<div style="clear: both;" ></div>

<div style="clear: both;" ></div>
  <input type="submit" name="skickat" value=" Skicka in " style="margin-top: 2em; margin-bottom: 2em;" />


</form>

<div style="clear: both;" ></div>
<p/>

Dina personuppgifter omfattas av sjukvårdslagen (SVL).
</div>
